### ISSUE TITLE
Allow KAI Logger to write to both stdout and a file

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai#110]
I've been grabbing the console stdout to include in various issues to aid debugging.
It'd be helpful if we write to both stdout and a file.

**Comment by aryansharma6827** [comment]
Hi I am Aryan and would like to contribute to this issue , can you please explain how to begin working on it and assign it to me.

**Comment by jwmatthews** [comment]
Hi @aryansharma6827 thank you for expressing interest.  This issue has been resolved as we now have logging of both file/console working.
