### ISSUE TITLE
Template 'mistralai/mixtral-8x7b-instruct-v01' not found. Falling back to main.jinja

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai#210]
We currently do not have specialized templates for most models, so it is normal and expected to see the below, yet we are logging this as an ERROR which will be misleading and confusing to new users.

`ERROR - 2024-06-26 06:22:09,278 - [   llm_io_handler.py:84   -           get_prompt()] - Template 'mistralai/mixtral-8x7b-instruct-v01' not found. Falling back to main.jinja
`

We should change the logging level to be something other than error

**Comment by gtyellow** [comment]
I'd like to take this on as my first issue.

**Comment by jwmatthews** [comment]
@gtyellow sounds great, if you run into questions getting Kai running locally let us know.

**Comment by JonahSussman** [comment]
Should be fixed by https://github.com/konveyor/kai/pull/232. Changed it to `DEBUG` as opposed to `INFO`. https://github.com/konveyor/kai/blob/737f1e96a0f6fe636b4154daf2a2869a60320923/kai/service/kai_application/util.py#L78-L83
