### ISSUE TITLE
[Docs] Update demo.md to specifically call out how to invoke with our custom rules

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai#212]
We need to update the doc here:  https://github.com/konveyor-ecosystem/kai/blob/main/docs/demo.md

Currently it talks about running analysis but doesn't explicitly call out the need for the custom rules, to help others avoid questions, let's be explicit

This is how we run analysis:
https://github.com/konveyor-ecosystem/kai/blob/main/example/analyze.sh

We are using custom rules here:
https://github.com/konveyor-ecosystem/kai/tree/main/samples/custom_rules

Further... you will notice in https://github.com/konveyor-ecosystem/kai/blob/main/example/analyze.sh that we are also IGNORING the default rules baked in Kantra and overriding with https://github.com/konveyor-ecosystem/kai/tree/main/example/default_rules

The original intent of overriding what Kantra included by default was so we could tweak some of the included rules as we experimented.

As of June 2024, I am unsure we need to override the default rules.  I would say for terms of the demo doc, we just focus on the 'custom_rules' which are essential and provide needed pieces for our Java EE to Quarkus path.  

We can revisit to add the overridden default rules if needed, but as of today I am not sure this is required.

**Comment by Manya-tech** [comment]
Hello John,
I am Manya Gupta. I recently came to know about Konveyor. I really like this application and have been exploring it's repositories. I would love to contribute and this seems like a good first issue for me. I would like to start working on it. Is anyone else working on this already?

**Comment by jwmatthews** [comment]
Hi @Manya-tech!

@savitharaghunathan has done some work which I think is related to this at https://github.com/konveyor/kai/blob/main/docs/customApps.md

I will defer to @savitharaghunathan to share where we are with this issue and what next steps may be.

The team will be happy to help you get onboarded for contributing.  If you run into any issues and want to chat in slack, you can reach us in  [ #konveyor-dev](https://kubernetes.slack.com/archives/C04QZJFQ0UA).  [Slack invite link here](https://communityinviter.com/apps/kubernetes/community)

**Comment by Manya-tech** [comment]
Thank you @jwmatthews!
I have joined the slack channel. Looking forward to contributing!
