### ISSUE TITLE
Update docs for how we manage python project dependencies

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai#273]
We need to update documentation as we recently changed how we manage python project dependencies

This could be a good first-issue for a new contributor who is versed in Python and is able to walk through the current install instructions, look at and understand #255, and then update the existing locations in our instructions.  I attempted to capture the 2 places I can think of below.

Update:

- Guidance on how to add modify a python dependency:  https://github.com/konveyor/kai/blob/main/CONTRIBUTING.md#updating-requirementstxt
- Guidance on installing dependencies in a virtual environment: https://github.com/konveyor/kai/blob/main/docs/contrib/Dev_Environment.md#local-development

with info from #255

example

**To install all dependencies in a new environment:**
- `python -m venv <venv-name>`
- `source <venv-name>/bin/activate`
- `pip install pip-tools`
- `pip-compile --allow-unsafe`
- `pip install -r requirements.txt`

**To add a new dependency to the project:**
- Add it to `requirements.in`
- `pip-compile --allow-unsafe`
- `pip install -r requirements.txt`

---

**Comment by brf153** [comment]
@jwmatthews is the issue resolved?

**Comment by jwmatthews** [comment]
> @jwmatthews is the issue resolved?

No, this is still open and available for anyone who is interested

**Comment by brf153** [comment]
@jwmatthews i am working on it
