### ISSUE TITLE
Issue: `process_log_dir_replacements` Function Not Handling Relative Paths Correctly

### ISSUE THREAD

**Issue by brf153** [konveyor/kai#278]
## Description
The `process_log_dir_replacements` function is intended to replace $pwd in log_dir with the location of the Kai project directory, which is one level up from the current script's location. However, the function is currently not working as expected. It returns paths with redundant or incorrect components, causing errors in path resolution.

## Expected Behavior
When $pwd is replaced with the Kai project directory, the resulting path should be an absolute path without redundant parts. For example, if the current working directory is /home/k8smaster/Desktop/kai/kai, and the log directory placeholder is $pwd/../logs, the expected output should be /home/k8smaster/Desktop/kai/logs.

## Actual Behavior
The function returns paths that include redundant components, such as /home/k8smaster/Desktop/kai/kai/..//logs, rather than the clean path /home/k8smaster/Desktop/kai/logs.

## Error Message
![image](https://github.com/user-attachments/assets/6b13c8ff-cee5-43aa-81a9-596f8f46388a)

## System
Ubuntu 22.04

**Comment by brf153** [comment]
Hello @jwmatthews,

Thank you for the feedback. I was writing unit tests for kai_logging.py. While testing the function process_log_dir_replacements, I came across this error. The relevant part of my test code is below:
```
class TestLoggingSetup(unittest.TestCase):
    def setUp(self):
        self.test_log_dir = tempfile.mkdtemp()
        self.console_log_level = "INFO"
        self.file_log_level = "DEBUG"
        self.log_file = "kai_server.log"
        self.log_dir_with_placeholder = "$pwd/logs"

        # Mock KaiConfig
        self.config = MagicMock(spec=KaiConfig)
        self.config.log_level = self.console_log_level
        self.config.file_log_level = self.file_log_level
        self.config.log_dir = self.log_dir_with_placeholder
        self.config.incident_store = MagicMock(spec=KaiConfigIncidentStore)
        self.config.models = KaiConfigModels(
            provider="FakeProvider",
            args={},
        )
        self.config.solution_consumers = []

    def tearDown(self):
        shutil.rmtree(self.test_log_dir)

    @patch('os.getcwd')
    def test_process_log_dir_replacements(self, mock_getcwd):
        mock_getcwd.return_value = '/home/k8smaster/Desktop/kai/kai'
        print(f"Mocked getcwd: {mock_getcwd.return_value}")
        print(f"Original log_dir: {self.config.log_dir}")
        
        actual_log_dir = process_log_dir_replacements(self.config.log_dir)
        
        print(f"Processed log_dir: {actual_log_dir}")
        expected_log_dir = '/home/k8smaster/Desktop/kai/logs'
        print(f"Expected log_dir: {expected_log_dir}")
        
        self.assertEqual(expected_log_dir, actual_log_dir)
 ```
Please note that the directories are hard-coded for testing purposes. The issue was that the processed log directory did not resolve correctly.

My Environment:

- Operating System: Ubuntu 22.04
- Python Version: Python 3.12

**Comment by jwmatthews** [comment]
Thank you @brf153, this helped clarify.  
Nicely done with the test example.
