### ISSUE TITLE
Solved examples are stored with a wrong ruleset name making them undiscoverable when using analysis outputs that use Konveyor rulesets

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/kai#299]
I used `make load-data` to load solved example data into Postgres. 

I discovered that some of these violations are stored with a different ruleset name than what we see with Konveyor rulesets. I do not know source of the issue. But here's an example:

```
> select violation_name, ruleset_name from violations where violation_name='jms-to-reactive-quarkus-00040';

│        violation_name         | ruleset_name 
│-------------------------------+--------------
│ jms-to-reactive-quarkus-00040 | kai/quarkus
```

`kai/quarkus` ruleset is not what we ship with Konveyor. So anytime you use analysis output that has this violation, the solved example won't be picked up because discovery works by looking at both violation name and ruleset name.

**Comment by jwmatthews** [comment]
Wonder if this is due to our custom rules ended up being submitted back to Konveyor.   Likely we have similar rules in two different names now.

**Comment by jwmatthews** [comment]
For background...

@jmle helped us to create the original rules we use in Kai for Quarkus, work was done initially here:
https://github.com/jmle/kai-examples/blob/main/coolstore-examples/examples.md

In time we copied the rules over to Kai here:
https://github.com/konveyor/kai/tree/main/samples/custom_rules

All of our scripts used those custom_rules for Quarkus, they did not exist in Kantra/Konveyor
In time, I assume the rules got submitted to Konveyor, so now we have a duplication of the custom rules in 2 places.

The analysis data that is used by `make load-data` comes from the below script
https://github.com/konveyor/kai/blob/main/samples/analyze_apps.py#L83

Both analysis runs of the data for `make load-data` and from the Client (IDE or run_demo.py) will use the custom rules at:
https://github.com/konveyor/kai/tree/main/samples/custom_rules

**NOTE:** For the runs with `run_demo.py` we are setup a little different, we IGNORE the default Kantra rules:
https://github.com/konveyor/kai/blob/main/example/analyze.sh#L50
run_demo.py then ends up using a submit of MODIFIED default rules from ~4 months ago based on what Konveyor had in rulesets at that point in time:
https://github.com/konveyor/kai/tree/main/example/default_rules/quarkus

So... we have potential for some slight differences in testing if we run from run_demo.py vs from IDE, as with IDE flow I don't believe we allow to skip the inclusion of default rules.


### Details ### 

From Kai Custom Rules:

https://github.com/konveyor/kai/blob/main/samples/custom_rules/ruleset.yaml
`name: kai/quarkus`

https://github.com/konveyor/kai/blob/main/samples/custom_rules/01-jms-to-reactive-quarkus.windup.yaml#L134
`ruleID: jms-to-reactive-quarkus-00040`


From Konveyor's ruleset directory:

https://github.com/konveyor/rulesets/blob/main/default/generated/quarkus/ruleset.yaml
`name: quarkus/springboot`

https://github.com/konveyor/rulesets/blob/main/default/generated/quarkus/218-jms-to-reactive-quarkus.windup.yaml#L123
`ruleID: jms-to-reactive-quarkus-00040`

**Comment by jwmatthews** [comment]
@pranavgaikwad I can work to clean this up.

I think what we should do is:
1) Remove the redundant quarkus rules, so if the rule exists in Konveyor's ruleset, will remove from Kai directory.  I think this means we will NOT need the custom rules as long as we are using a recent Kantra, will assume v0.5.0+.
2) Will keep the mechanism/script to include the custom_rules directory, but assume it will be empty
3) Will re-run analysis for all of the sample apps, then will update that analysis data committed to the repo
4) Will do similar for the run_example.py analysis setup to re-run.  

I'm unsure if the modified rules we used in https://github.com/konveyor/kai/tree/main/example/default_rules/quarkus are of use, this was an experiment where we wanted to explore if modified rules with greater hints would benefit us.  Not sure if we had time to expand to see the benefit.  Potential to simplify and remove if this gets to be confusing.

**Comment by pranavgaikwad** [comment]
@jwmatthews thank you, that should solve this issue.
