### ISSUE TITLE
Add support for Google Gemini models

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai#304]
We would like to add support for Google Gemini models.  This may be a more challenging 'good first issue' as to add this in will require some understanding of how Kai is interfacing with LLMs, yet the work is likely to be relatively easy.

For example, you can look at this PR to see how Amazon Bedrock was added to Kai:
https://github.com/konveyor/kai/pull/289/files

The work for adding a new model endpoint is to find an approach compatible with langchain, likely will mean adding a new package and small change to [kai/service/llm_interfacing/model_provider.py](https://github.com/konveyor/kai/blob/main/kai/service/llm_interfacing/model_provider.py) and [kai/config.toml](https://github.com/konveyor/kai/blob/main/kai/config.toml)

**Comment by Myrausman** [comment]
I'm interested in working on this. Could you please assign me this issue?
