### ISSUE TITLE
Stopping `make run-server` does not stop cleanly:  "Python quit unexpectedly"

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai#305]
On MacOS when I 'ctrl-c' the `make run-server` process I receive a popup window that:  "Python quit unexpectedly".

<img width="988" alt="Screenshot 2024-08-18 at 6 35 03 AM" src="https://github.com/user-attachments/assets/84ff9ddf-6c93-4e86-9265-5877461a36a9">

Full output:  https://gist.github.com/jwmatthews/c5d332a7ed955b946eb8ce8288af0306

**Comment by jwmatthews** [comment]
My guess is that this issue is related to how we are using [gunicorn](https://gunicorn.org/).  Perhaps we need to implement a hook to watch for SIGINT and then implement a graceful shutdown.

**Comment by jmontleon** [comment]
When the main process receives the SIGINT. The workers receive SIGQUIT. 

gunicorn has callables on_exit and on_worker_exit. I'm not sure these are helpful yet.

SIGTERM seems to cause a graceful shutdown:
```
[2024-09-16 13:28:10 -0400] [679457] [INFO] Handling signal: term
[2024-09-16 13:28:10 -0400] [679555] [INFO] Worker exiting (pid: 679555)
[2024-09-16 13:28:10 -0400] [679556] [INFO] Worker exiting (pid: 679556)
[2024-09-16 13:28:10 -0400] [679557] [INFO] Worker exiting (pid: 679557)
[2024-09-16 13:28:10 -0400] [679558] [INFO] Worker exiting (pid: 679558)
[2024-09-16 13:28:10 -0400] [679559] [INFO] Worker exiting (pid: 679559)
[2024-09-16 13:28:10 -0400] [679560] [INFO] Worker exiting (pid: 679560)
[2024-09-16 13:28:10 -0400] [679561] [INFO] Worker exiting (pid: 679561)
[2024-09-16 13:28:10 -0400] [679566] [INFO] Worker exiting (pid: 679566)
[2024-09-16 13:28:11 -0400] [679457] [INFO] Shutting down: Master
```

**Comment by jmontleon** [comment]
https://docs.gunicorn.org/en/latest/signals.html#worker-process

Also, fwiw gunicorn is handling them. Their intention however is that SIGINT is for a quick non-graceful shutdown, not to say we can't try to do something, but still trying to come up with a solution.

**Comment by jmontleon** [comment]
I'm going to have a look at understanding how to deploy a mac instance in AWS with. https://github.com/konveyor/kai/issues/347 in mind. I'll give this a test while doing that.

**Comment by jmontleon** [comment]
These appear to go away with the linked PR to fix the SIGKILLS, but if SIGINT causes `python quit unexpectedly` errors to return this was working prior to the SIGKILL issue arriving:
```
run-server:
	bash -c 'set -m; _trap () { kill -15 $$PID; } ; trap _trap SIGINT ;\
	PYTHONPATH=$(KAI_PYTHON_PATH) python kai/server.py & export PID=$$! ;\
	while kill -0 $$PID > /dev/null 2>&1; do wait $$PID; done'
```

**Comment by jwmatthews** [comment]
I am reopening this as I still see the problem even with #367 on MacOS
Output from last time I saw this:  https://gist.github.com/jwmatthews/c353df2178999ca37f9a7ea5bb37d300

**Comment by jmontleon** [comment]
Alright, I'll PR the trap to initiate a gracefully shutdown (above) in addition to the crash workaround.
