### ISSUE TITLE
Develop a script that seeds Kai/Konveyor with analysis history

### ISSUE THREAD

**Issue by dymurray** [konveyor/kai#360]
- Simulate a scenario where we have 2 years of data
- 10/15 apps
- Start on an older branch, run analysis
- Simulate code change
- Rerun analysis
- Deliver this as a script that all devs can use to prepopulate data

**Comment by sshveta** [comment]
@abrugaro Assigning this to you .

**Comment by abrugaro** [comment]
Hi @dymurray,

Just to confirm, the goal is to simulate changes applied to multiple applications over time. The script should:

1. Create N apps using an older branch
2. Analyze them
3. Edit the branch to select a more recent version to simulate the code changes
4. Analyze them again

Is that right?

Also, I'm creating the script assuming that auth is disabled in Konveyor when the script is executed. Is that acceptable?

Thanks!

**Comment by dymurray** [comment]
@abrugaro that's exactly right. It is probably worth stepping through the example with one application and 3-4 iterations of code changes. I think the majority of the work here will be focusing on finding a few good example applications that we understand the historical changes well enough to be able to sanity check the results.

There is also some possibility to leverage @jortel and @mansam 's [Hub snapshot](https://github.com/konveyor/tackle2-hub/issues/565) work to be able to seed a Konveyor instance with the analysis history.

If we can find a few good example apps with code changes that fix specific incidents then this is where we can get valuable data exposed within Kai.

cc @jwmatthews if I'm missing something

**Comment by abrugaro** [comment]
PR merged, the script can be found [here](https://github.com/konveyor/kai-ci/blob/main/populate-konveyor.sh)
