### ISSUE TITLE
Capture LLM requests using vcr.py

### ISSUE THREAD

**Issue by fabianvf** [konveyor/kai#69]
This will allow us to write tests that 
a) don't require valid API keys
b) aren't dependent on the stability/availability of various AI providers
c) aren't super slow because we're waiting for the LLMs to generate information for real

**Comment by jwmatthews** [comment]
Closing as we implemented vcr functionality to cache LLM calls in ~April 2024

We cache data here:
https://github.com/konveyor/kai/tree/main/kai/data/vcr
